[package]
name = "concept"
version = "0.1.0"
edition = "2021"

[dependencies]
rfd = "0.10.0"
base64 = "0.21.0"
reqwest = { version = "0.11", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }